Test push to ASG v 2.0

diff --git a/.github/workflows/deploy-target-group-test-frontend.yml b/.github/workflows/deploy-target-group-test-frontend.yml
--- a/.github/workflows/deploy-target-group-test-frontend.yml
+++ b/.github/workflows/deploy-target-group-test-frontend.yml
@@ -66,39 +66,6 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
 
-      - name: Set up check_command_status script
-        run: |
-          cat <<- 'EOF' > /tmp/check_command_status.sh
-          #!/bin/bash
-          check_command_status () {
-            local command_id=$1
-            local instance=$2
-            local status="Pending"
-            while [[ "$status" == "Pending" || "$status" == "InProgress" ]]; do
-              status=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance" --query 'Status' --output text 2>/dev/null)
-              if [ -z "$status" ]; then
-                status="Pending"
-              fi
-              echo "Command $command_id status on instance $instance: $status"
-              sleep 5
-            done
-            # После завершения команды выводим стандартный вывод и ошибки
-            output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance" --query 'StandardOutputContent' --output text)
-            error_output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance" --query 'StandardErrorContent' --output text)
-            if [[ "$status" != "Success" ]]; then
-              echo "Command $command_id failed with status: $status"
-              echo "Standard Error:"
-              echo "$error_output"
-              exit 1
-            else
-              echo "Command $command_id succeeded with status: $status"
-              echo "Standard Output:"
-              echo "$output"
-            fi
-          }
-          export -f check_command_status
-          EOF
-
       - name: Get EC2 instances in Target Group
         id: get_instances
         run: |
@@ -106,15 +73,16 @@ jobs:
           echo "Instances found: $instances"
           echo "instances=$instances" >> $GITHUB_OUTPUT
 
-      - name: Pull latest Docker image
+      - name: Deploy to Instances
         env:
           AWS_REGION: ${{ vars.AWS_REGION }}
           IMAGE_FULL_NAME: '${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY_TEST }}:${{ github.ref_name }}-latest'
         run: |
-          source /tmp/check_command_status.sh
           instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
+          for instance in $instances; do
+            echo "Deploying to instance: $instance"
+
+            # Pull latest Docker image
             echo "Pulling Docker image on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
@@ -125,17 +93,9 @@ jobs:
               --region "$AWS_REGION" \
               --query "Command.CommandId" \
               --output text)
-            check_command_status "$command_id" "$instance"
-          done
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
 
-      - name: Stop running containers using docker-compose down
-        env:
-          AWS_REGION: ${{ vars.AWS_REGION }}
-        run: |
-          source /tmp/check_command_status.sh
-          instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
+            # Stop running containers
             echo "Stopping containers on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
@@ -146,17 +106,9 @@ jobs:
               --region "$AWS_REGION" \
               --query "Command.CommandId" \
               --output text)
-            check_command_status "$command_id" "$instance"
-          done
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
 
-      - name: Start containers using docker-compose up -d
-        env:
-          AWS_REGION: ${{ vars.AWS_REGION }}
-        run: |
-          source /tmp/check_command_status.sh
-          instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
+            # Start containers
             echo "Starting containers on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
@@ -167,17 +119,9 @@ jobs:
               --region "$AWS_REGION" \
               --query "Command.CommandId" \
               --output text)
-            check_command_status "$command_id" "$instance"
-          done
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
 
-      - name: Remove unused Docker images
-        env:
-          AWS_REGION: ${{ vars.AWS_REGION }}
-        run: |
-          source /tmp/check_command_status.sh
-          instances="${{ steps.get_instances.outputs.instances }}"
-          for instance in $instances
-          do
+            # Remove unused Docker images
             echo "Pruning Docker images on instance: $instance"
             command_id=$(aws ssm send-command \
               --instance-ids "$instance" \
@@ -188,5 +132,36 @@ jobs:
               --region "$AWS_REGION" \
               --query "Command.CommandId" \
               --output text)
-            check_command_status "$command_id" "$instance"
+            ./wait_for_ssm_command.sh "$command_id" "$instance"
           done
+
+      - name: wait_for_ssm_command.sh
+        shell: bash
+        run: |
+          cat << 'EOF' > wait_for_ssm_command.sh
+          #!/bin/bash
+          command_id=$1
+          instance_id=$2
+          status="Pending"
+          while [[ "$status" == "Pending" || "$status" == "InProgress" ]]; do
+            status=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance_id" --query 'Status' --output text 2>/dev/null)
+            if [ -z "$status" ]; then
+              status="Pending"
+            fi
+            echo "Command $command_id status on instance $instance_id: $status"
+            sleep 5
+          done
+          output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance_id" --query 'StandardOutputContent' --output text)
+          error_output=$(aws ssm get-command-invocation --command-id "$command_id" --instance-id "$instance_id" --query 'StandardErrorContent' --output text)
+          if [[ "$status" != "Success" ]]; then
+            echo "Command $command_id failed with status: $status"
+            echo "Standard Error:"
+            echo "$error_output"
+            exit 1
+          else
+            echo "Command $command_id succeeded with status: $status"
+            echo "Standard Output:"
+            echo "$output"
+          fi
+          EOF
+          chmod +x wait_for_ssm_command.sh
